In [ ]:
import numpy as np
arr = np.arange(1,7).reshape(2,3)

In [ ]:
arr.sum()

21

In [ ]:
print('위메이드 떡상')

위메이드 떡상


In [ ]:
arr.sum(axis=0)
np.sum(arr,axis=0)

array([5, 7, 9])

In [ ]:
arr.sum(axis=1)

array([ 6, 15])

In [ ]:
print(arr)
print(arr.shape)
arr.sum()

[[1 2 3]
 [4 5 6]]
(2, 3)


21

In [ ]:
arr.sum(axis=0)
np.sum(arr,axis=0)

array([5, 7, 9])

In [ ]:
arr.sum(axis=1)
np.sum(arr,axis=1)

array([ 6, 15])

In [ ]:
arr = np.arange(1,19).reshape(3,2,3)

In [ ]:
arr.sum(axis=0).shape

(2, 3)

In [ ]:
arr.sum(axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3

In [ ]:
arr = np.arange(1,7).reshape(2,3)

In [ ]:
arr.mean(axis=0)
np.around(arr.std(axis=1),2)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [ ]:
np.std(arr,axis=1)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

In [ ]:
arr.std(axis=1).around(2)

AttributeError: 'numpy.ndarray' object has no attribute 'around'

In [ ]:
np.exp(arr)
# np.exp(arr,axis=0)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]],

       [[4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]]])

In [ ]:
np.log(arr)

array([[[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]],

       [[1.94591015, 2.07944154, 2.19722458],
        [2.30258509, 2.39789527, 2.48490665]],

       [[2.56494936, 2.63905733, 2.7080502 ],
        [2.77258872, 2.83321334, 2.89037176]]])

In [ ]:
np.log(np.exp(arr))

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]])

In [ ]:
arr1 = np.arange(1,5).reshape(4,1)
arr2 = np.arange(5,9).reshape(4,1) 

In [ ]:
print(arr1)
print(arr2)

[[1]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [7]
 [8]]


In [ ]:
np.sqrt((arr1 - arr2)**2)

array([[4.],
       [4.],
       [4.],
       [4.]])

In [ ]:
arr = np.random.randint(1,100,5)

In [ ]:
arr.sort()

In [ ]:
arr

array([ 9, 13, 31, 54, 98])

In [ ]:
np.sort(arr)

array([ 9, 13, 31, 54, 98])

In [ ]:
np.sort(arr)

array([ 9, 13, 31, 54, 98])

In [ ]:
arr[np.argsort(arr)]

array([ 9, 13, 31, 54, 98])

In [ ]:
arr = np.random.randint(1,5,10).reshape(5,2)

In [ ]:
arr[np.argsort(arr[0]),:]

array([[3, 4],
       [2, 1]])

In [ ]:
arr[np.argsort(arr[:,0]),:]

array([[1, 1],
       [2, 1],
       [2, 3],
       [2, 2],
       [3, 4]])

In [ ]:
arr[np.argsort(arr[:,0]),:]

array([[1, 1],
       [2, 1],
       [2, 3],
       [2, 2],
       [3, 4]])

In [ ]:
arr[[1,2,4,3,0],:]

array([[2, 1],
       [2, 3],
       [1, 1],
       [2, 2],
       [3, 4]])

In [ ]:
arr[np.argsort(arr[:,0]),:]
arr[np.argsort(arr[:,0])[::-1],:]

array([[3, 4],
       [2, 2],
       [2, 3],
       [2, 1],
       [1, 1]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)

[1 2 3]
(3,)
[4 5 6]
(3,)


In [ ]:
arr3 = np.vstack((arr1,arr2))
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
## 2차원의 vstack
arr1 = np.array([1,2,3]).reshape(1,3)
arr2 = np.array([[4,5,6],
                [7,8,9]])

In [ ]:
print(arr1.shape)
print(arr2.shape)

(1, 3)
(2, 3)


In [ ]:
arr1 = np.array([1,2,3]).reshape(3,1)
arr2 = np.array([4,5,6]).reshape(3,1)

In [ ]:
arr3 = np.hstack((arr1,arr2))

In [ ]:
arr3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
arr4 = np.hstack((arr3,arr1))

In [ ]:
arr4

array([[1, 4, 1],
       [2, 5, 2],
       [3, 6, 3]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([1,2,3]).reshape(3,1)
arr2 = np.array([4,5,6])

In [ ]:
np.hstack((arr1,arr2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.concatenate((arr1,arr2))
# shape -target(1차원과,2차원 정의), target2(1차원, 2차원) 
arr1 = np.array([1,2,3]).reshape(1,3)
arr2 = np.array([4,5,6]).reshape(1,3)
np.concatenate((arr1,arr2),axis=0)
np.concatenate((arr1,arr2),axis=1)
# np.concatenate((arr1,arr2),axis=0)

In [ ]:
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.array([[5,6]])

In [ ]:
arr1

array([[1],
       [2],
       [3]])

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
arr3 = np.concatenate((arr1,arr2),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
arr2.transpose()

In [ ]:
arr4 = np.concatenate((arr1,arr2.transpose()),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
arr5 = np.concatenate((arr1,arr2.T),axis=1)

In [ ]:
print(arr4)
print(arr5)

[[1 4 1]
 [2 5 2]
 [3 6 3]]
[[1 2 3]]


In [ ]:
## broadcast
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(11,17).reshape(2,3)

In [ ]:
# # broadcast scalar
# arr1 + 1
# arr < 4
# # broadcast element
# arr3 = np.array([1,2]).reshape(2,-1)
# arr1 + arr3
# arr4 = np.array([1,2]).reshape(-1,2)
# arr1 + arr3
# arr4 = np.array([1,2]).reshape(-1,2)
# try:
#     arr1 + arr4
# except:
#     print('err')
# arr5 = np.array([1,2,3]).reshape(1,3)

# arr1 + arr5 
# # element-wise
# arr1 + arr2
# # brodacast-element
# arr1.reshape(-1,6)+arr2.reshape(6,-1)
# # dot --martix multiply
# # element multiply
# arr1 * arr2
# np.dot(arr1,arr2.T)
# ## matrix
# m1 = np.matrix(arr1)
# m2 = np.matirx(arr2)
# tprint(np.dot(arr1,arr2.T))
# print(m1*m2.T)

# broadcast scalar
arr1 + 1 
arr1 < 4
# broadcast element
arr3 = np.array([1,2]).reshape(2,-1)
arr1 + arr3
arr4 = np.array([1,2]).reshape(-1,2)
try:
    arr1 + arr4
except:
    print('err')
arr5 = np.array([1,2,3]).reshape(1,3)
arr1 + arr5
# element-wise
arr1 + arr2
# broadcast-element
arr1.reshape(-1,6)+arr2.reshape(6,-1)
## dot -- matrix multiply
# element multiply
arr1 * arr2
np.dot(arr1,arr2.T)
## matrix
m1 = np.matrix(arr1)
m2 = np.matrix(arr2)
print(arr1*arr2)
print(np.dot(arr1,arr2.T))
print(m1*m2.T)

err
[[11 24 39]
 [56 75 96]]
[[ 74  92]
 [182 227]]
[[ 74  92]
 [182 227]]


In [ ]:
import numpy as np

In [ ]:
def dot(m1,m2):
    if m1.shape[1] !=m2.shape[0]:
        return 'shape 이 맞지 않습니다'
    m3 = np.zeros((m1.shape[0],m2.shape[1]))
    for i in range(m1.shape[0]):
        for j in range(m2.shape[1]):
            m3[i,j] = m1[i,:]*m2[:,j]
    return m3

In [ ]:
arr = np.arange(1,11)
np.any(arr < 10)

True

In [ ]:
arr = np.arange(1,11)
np.any(arr < 10)
np.all(arr < 12)

True

In [ ]:
# any의 의미
sum(arr < 10) >= 1

True

In [ ]:
#all의 의미
sum(arr < 11)/arr.size == 1

True

In [ ]:
a = np.array([1,2,3])
b = np.array([3,2,1])

In [ ]:
a == b

array([False,  True, False])

In [ ]:
a[[False,True,False]]

array([2])

In [ ]:
a[(a<3) & (a>1)]

array([2])

In [ ]:
a[np.logical_and(a < 3 , a >1)]
## np.logical_or, np.logical_not

array([2])

In [ ]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
np.where??

Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
-

In [ ]:
# np.where
np.random.seed(3)
korea = np.random.randint(60,100,100)

In [ ]:
result = []
for i in korea:
    if i > 70:
        result.append('pass')
    else:
        result.append('fail')
result

['pass',
 'fail',
 'fail',
 'fail',
 'pass',
 'pass',
 'fail',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'fail',
 'fail',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'fail',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'fail',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'fail',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'pass',
 'fail',
 'pass',
 'pass',
 'pass']

In [ ]:
result = np.where(korea>70,'pass','fail')

In [ ]:
result

array(['pass', 'fail', 'fail', 'fail', 'pass', 'pass', 'fail', 'fail',
       'pass', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass',
       'pass', 'pass', 'pass', 'fail', 'fail', 'fail', 'pass', 'fail',
       'pass', 'pass', 'pass', 'fail', 'pass', 'pass', 'pass', 'pass',
       'pass', 'pass', 'pass', 'pass', 'fail', 'fail', 'pass', 'pass',
       'fail', 'pass', 'pass', 'fail', 'pass', 'fail', 'pass', 'pass',
       'pass', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass',
       'pass', 'pass', 'pass', 'pass', 'pass', 'fail', 'pass', 'pass',
       'pass', 'fail', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass',
       'fail', 'pass', 'pass', 'pass', 'pass', 'fail', 'pass', 'pass',
       'fail', 'pass', 'pass', 'pass', 'pass', 'fail', 'pass', 'fail',
       'pass', 'fail', 'pass', 'pass', 'pass', 'pass', 'pass', 'pass',
       'fail', 'pass', 'pass', 'pass'], dtype='<U4')

In [ ]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [ ]:
np.random.seed(3)
korea = np.random.randint(60,100,1_000_000)

In [ ]:
%%time
## 
result = []
for i in korea:
    if i > 70:
        result.append('pass')
    else:
        result.append('fail')

Wall time: 308 ms


In [ ]:
%%time
result = np.where(korea>70,'pass','fail')

Wall time: 10.1 ms


In [ ]:
np.random.seed(3)
korea = np.random.randint(60,100,1_000_000)

In [567]:
%%time
## 90 이상이면 A, 80 B, 70 C, 나머지D
result = []
for i in korea:
    if i >= 90:
        result.append('A')
    elif i >= 80:
        result.append('B')
    elif i >=70:
        result.append('C')
    else:
        result.append('D')

Wall time: 498 ms


In [568]:
%%time
result = np.where(korea >= 90,'A',
                  np.where(korea >= 80,'B',
                          np.where(korea >=70,'C','D')))

Wall time: 15.4 ms


In [569]:
np.random.seed(3)
arr = np.random.randint(60,100,3000).reshape(1000,-1)

In [570]:
arr

array([[84, 63, 68],
       [60, 81, 79],
       [70, 70, 81],
       ...,
       [73, 99, 63],
       [74, 63, 62],
       [96, 74, 64]])

In [571]:
arr1 = np.hstack((arr,np.argmax(arr,axis=1).reshape(1000,1)))

In [572]:
np.unique([1,1,2,3,3],return_counts=True)

(array([1, 2, 3]), array([2, 1, 2], dtype=int64))

In [573]:
np.unique([1,1,2,3,3],return_counts=True)

(array([1, 2, 3]), array([2, 1, 2], dtype=int64))

In [574]:
np.where(np.unique(arr1[:,3],return_counts=True)[1].argmax()==0,'국어',
         np.where(np.unique(arr1[:,3],return_counts=True)[1].argmax()==1,'수학','영어'))

array('국어', dtype='<U2')

In [575]:
np.save('arr.npy',arr1)

In [576]:
# arr = np.load('arr.npy')

In [ ]:
dir(np)
np.NAN

nan

In [ ]:
np.array([[1,2,3],[2,3,np.nan]])

array([[ 1.,  2.,  3.],
       [ 2.,  3., nan]])

In [ ]:
dir(np)
# l = np.array([1,2,3])
# np.append(l,4)
# l
# arr1 = np.arange(1,7)
# arr2 = np.arange(11,17)
# arr3 = np.arange(21,27)
# np.c_[arr1,arr2,arr3]
# arr1 = np.random.randint(3,10,7)
# print(arr1)
# print(np.cumsum(arr1))
# print(np.cumprod(arr1))
np.apply_along_axis??
arr1 = np.random.randn(4,3)
def min_minus(x):
    return x - np.min(x)
np.apply_along_axis(min_minus,1, arr1)
np.apply_along_axis(lambda x:x-np.min(x),1,arr1)

array([[1.35290936, 2.01118456, 0.        ],
       [0.83893581, 0.        , 2.19510893],
       [0.        , 1.63588347, 1.10764965],
       [1.48039655, 0.93270734, 0.        ]])

Signature: np.apply_along_axis(func1d, axis, arr, *args, **kwargs)
Source:   
@array_function_dispatch(_apply_along_axis_dispatcher)
def apply_along_axis(func1d, axis, arr, *args, **kwargs):
    """
    Apply a function to 1-D slices along the given axis.

    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.

    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]

    Equivalently, eliminating the inner loop, this can be expressed as::

        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for k

In [10]:
arr = np.array([1,2,3])
arr.reshape(-1,1)
arr[:,np.newaxis,np.newaxis]

array([[[1]],

       [[2]],

       [[3]]])

In [11]:
np.array([[1,2,3,],[2,3,np.nan]])

array([[ 1.,  2.,  3.],
       [ 2.,  3., nan]])

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# series
# dataframe
# np. array([1,2,3],dtype='int')
pd.Series([1,2,3],index=([1,2,3])
dic = {
    1:1
    2:2
    3:3
}
pd.Series(dic)

SyntaxError: invalid syntax (2697394987.py, line 5)

In [ ]:
pd.Series([1,2,3],index=[1,2,3])

In [ ]:
dic = {
    'one':1,
    'two':2,
    'three':3
}
s1 = pd.Series(dic)

In [ ]:
s1.index

Index(['one', 'two', 'three'], dtype='object')

In [ ]:
pd.Series([1,2,3],index=['one','two','three'])

one      1
two      2
three    3
dtype: int64

In [ ]:
s2 = pd.Series(['2019-01-02',3.14,'ABC',100,True])

In [ ]:
s2.dtype

dtype('O')

In [ ]:
s1[['one','three']]

one      1
three    3
dtype: int64

In [ ]:
dic = {
    'korean':[1,2,3],
    'eng':[4,5,6],
    'math':[7,8,9]
}
pd.DataFrame(dic,index=[1,2,3])

korean  eng  math
1       1    4     7
2       2    5     8
3       3    6     9

In [ ]:
kor = [1,2,3]
eng = [4,5,6]
math = [7,8,9]
dt = np.c_[kor,eng,math].T

In [ ]:
pd.DataFrame(dt,index=[1,2,3],
             columns=['kor','eng','math'])

kor  eng  math
1    1    2     3
2    4    5     6
3    7    8     9

In [ ]:
df = pd.DataFrame(dt)

In [ ]:
df.index = [1,2,3]
df.columns = ['kor','eng','math']

In [ ]:
df.index

Int64Index([1, 2, 3], dtype='int64')

In [ ]:
df.columns

Index(['kor', 'eng', 'math'], dtype='object')

In [ ]:
df.columns

Index(['kor', 'eng', 'math'], dtype='object')

In [ ]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df.rename(columns={'kor':'korean'},inplace=True)

In [ ]:
df.rename(index={1:10})

korean  eng  math
10       1    2     3
2        4    5     6
3        7    8     9

In [6]:
df.columns = [0,1,2]

In [229]:
dic = {
    1:np.random.randint(60,100,100),
    2:np.random.randint(60,100,100),
    3:np.random.randint(60,100,100),
    4:np.random.randint(60,100,100),
    5:np.random.randint(60,100,100),
    6:np.random.randint(60,100,100),
    7:np.random.randint(60,100,100),
    8:np.random.randint(60,100,100),
    9:np.random.randint(60,100,100),
    10:np.random.randint(60,100,100),
    11:np.random.randint(60,100,100),
    12:np.random.randint(60,100,100),
}

In [230]:
df = pd.DataFrame(dic)

In [231]:
df.columns = [ str(i)+'월' for i in df.columns ]

In [232]:
df.rename(columns={}) 

1월  2월  3월  4월  5월  6월  7월  8월  9월  10월  11월  12월
0   98  70  88  77  62  62  60  61  89   81   80   68
1   77  83  61  73  68  82  86  81  73   66   69   95
2   83  76  68  66  79  68  69  82  94   68   94   90
3   76  81  83  60  99  60  66  70  82   82   76   87
4   67  64  74  60  94  84  94  98  66   64   77   94
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...
95  97  78  89  64  86  67  63  68  96   78   91   60
96  63  82  82  90  82  60  91  78  91   82   67   75
97  75  64  63  86  67  69  80  86  75   77   85   73
98  81  72  65  70  90  67  81  71  62   94   91   98
99  80  94  99  93  86  75  66  62  88   89   68   82

[100 rows x 12 columns]

In [233]:
{ i:'0'+i for i in df.columns[df.columns.str.len() <3]}

{'1월': '01월',
 '2월': '02월',
 '3월': '03월',
 '4월': '04월',
 '5월': '05월',
 '6월': '06월',
 '7월': '07월',
 '8월': '08월',
 '9월': '09월'}

In [234]:
cols = df.columns[df.columns.str.len() <3]
col_dic = { i:'0'+i for i in cols }
df.rename(columns=col_dic,
          inplace=True) 

In [235]:
df.set_index(df['01월'],inplace=True)

In [236]:
df.drop(columns=['01월'],inplace=True)

In [237]:
df

02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월
01월                                                       
98    70   88   77   62   62   60   61   89   81   80   68
77    83   61   73   68   82   86   81   73   66   69   95
83    76   68   66   79   68   69   82   94   68   94   90
76    81   83   60   99   60   66   70   82   82   76   87
67    64   74   60   94   84   94   98   66   64   77   94
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
97    78   89   64   86   67   63   68   96   78   91   60
63    82   82   90   82   60   91   78   91   82   67   75
75    64   63   86   67   69   80   86   75   77   85   73
81    72   65   70   90   67   81   71   62   94   91   98
80    94   99   93   86   75   66   62   88   89   68   82

[100 rows x 11 columns]

In [238]:
df.reset_index(inplace=True)

In [239]:
df.drop(index=[0],axis=1)

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월
1    77   83   61   73   68   82   86   81   73   66   69   95
2    83   76   68   66   79   68   69   82   94   68   94   90
3    76   81   83   60   99   60   66   70   82   82   76   87
4    67   64   74   60   94   84   94   98   66   64   77   94
5    62   69   83   68   96   82   85   99   90   69   70   91
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
95   97   78   89   64   86   67   63   68   96   78   91   60
96   63   82   82   90   82   60   91   78   91   82   67   75
97   75   64   63   86   67   69   80   86   75   77   85   73
98   81   72   65   70   90   67   81   71   62   94   91   98
99   80   94   99   93   86   75   66   62   88   89   68   82

[99 rows x 12 columns]

In [240]:
df.drop(columns=['01월','03월'],axis=0)

02월  04월  05월  06월  07월  08월  09월  10월  11월  12월
0    70   77   62   62   60   61   89   81   80   68
1    83   73   68   82   86   81   73   66   69   95
2    76   66   79   68   69   82   94   68   94   90
3    81   60   99   60   66   70   82   82   76   87
4    64   60   94   84   94   98   66   64   77   94
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
95   78   64   86   67   63   68   96   78   91   60
96   82   90   82   60   91   78   91   82   67   75
97   64   86   67   69   80   86   75   77   85   73
98   72   70   90   67   81   71   62   94   91   98
99   94   93   86   75   66   62   88   89   68   82

[100 rows x 10 columns]

In [241]:
df['02월'][df['02월'] == 99].index

Int64Index([19], dtype='int64')

In [242]:
df['02월'] == 99

0     False
1     False
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Name: 02월, Length: 100, dtype: bool

In [243]:
print('집중력이 바닥입니다 쉬세요')

집중력이 바닥입니다 쉬세요


In [244]:
df.loc[[0,2,4],['01월','02월']]

01월  02월
0   98   70
2   83   76
4   67   64

In [245]:
df.iloc[[0,2,4],[-1]]

12월
0   68
2   90
4   94

In [246]:
# 짝수번째 데이터만 가져오기
df.loc[[0,2,4,6,8,10],['01월','02월']]

01월  02월
0    98   70
2    83   76
4    67   64
6    91   78
8    77   68
10   71   71

In [247]:
df.loc[df.index %2 == 0 ,['01월','02월']]

01월  02월
0    98   70
2    83   76
4    67   64
6    91   78
8    77   68
10   71   71
12   62   97
14   73   93
16   96   95
18   99   75
20   61   78
22   68   84
24   84   72
26   67   66
28   98   92
30   89   88
32   72   83
34   89   60
36   77   81
38   69   64
40   81   77
42   61   73
44   84   71
46   94   67
48   77   71
50   85   69
52   60   76
54   97   94
56   78   76
58   60   82
60   93   79
62   76   70
64   83   61
66   69   76
68   65   80
70   95   98
72   86   98
74   87   66
76   70   71
78   83   79
80   87   95
82   84   85
84   63   67
86   73   79
88   92   97
90   85   98
92   65   79
94   96   61
96   63   82
98   81   72

In [248]:
# # 짝수데이터의 짝수월만 가져오기
# df.loc[df.index % 2 ==0, ['02월','04월','06월','08월','10월','12월']]
# df.loc[df.index % 2 ==0,[1,3,5,7,9,11]]
# clos = (pd.Series(df.colums).index % 2 == 1)
# df.iloc[df.index % 2 ==0,cols]
# cols = np.arange(1,df.columns.size+1,2)
# df.iloc[df.index %2 ==0, cols]

# 짝수번째 데이터만 가져오기
df.iloc[df.index % 2 == 0,:]
# 짝수데이터의 짝수월만 가져오기
df.iloc[df.index % 2 ==0,[1,3,5,7,9,11]]
cols = (pd.Series(df.columns).index % 2 == 1)
df.iloc[df.index % 2 ==0,cols]
cols = np.arange(1,df.columns.size+1,2)
df.iloc[df.index %2 ==0, cols]

02월  04월  06월  08월  10월  12월
0    70   77   62   61   81   68
2    76   66   68   82   68   90
4    64   60   84   98   64   94
6    78   97   79   95   70   69
8    68   62   90   65   81   79
10   71   72   95   62   65   80
12   97   66   96   67   95   70
14   93   78   91   95   70   79
16   95   64   77   92   71   84
18   75   82   83   81   92   86
20   78   74   67   77   81   81
22   84   81   97   94   68   65
24   72   81   84   91   77   78
26   66   84   66   82   76   88
28   92   60   96   71   76   61
30   88   68   70   90   89   88
32   83   99   96   92   68   64
34   60   64   94   74   82   90
36   81   81   99   98   95   88
38   64   92   89   97   85   73
40   77   95   60   87   80   99
42   73   68   97   77   63   70
44   71   93   76   87   79   78
46   67   61   97   96   66   91
48   71   93   93   89   64   96
50   69   97   89   79   97   87
52   76   73   73   68   82   92
54   94   61   97   89   84   98
56   76   91   96   67   95   94
58   82   81   98   66   87   72
60   79   97   97   91   69   73
62   70   98   92   68   69   63
64   61   99   95   95   74   82
66   76   65   79   95   81   94
68   80   80   92   84   92   86
70   98   82   97   90   80   65
72   98   91   87   81   67   75
74   66   66   84   73   71   68
76   71   66   62   96   74   76
78   79   62   89   98   92   78
80   95   77   78   66   70   91
82   85   68   72   83   75   99
84   67   91   63   98   92   69
86   79   66   75   94   98   71
88   97   68   61   69   96   70
90   98   65   90   81   95   80
92   79   98   61   67   81   95
94   61   86   62   74   60   93
96   82   90   60   78   82   75
98   72   70   67   71   94   98

In [249]:
df['total'] = df.values.sum(axis=1)

In [250]:
df.iloc[:,:-1].mean(axis=1)

0     74.666667
1     76.166667
2     78.083333
3     76.833333
4     78.000000
        ...    
95    78.083333
96    78.583333
97    75.000000
98    78.500000
99    81.833333
Length: 100, dtype: float64

In [251]:
df['avg'] = df.iloc[:,:-1].mean(axis=1)

In [252]:
df['best_month'] = df.columns[np.argmax(df.iloc[:,:-2].values,axis=1)]

In [253]:
df

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
0    98   70   88   77   62   62   60   61   89   81   80   68    896   
1    77   83   61   73   68   82   86   81   73   66   69   95    914   
2    83   76   68   66   79   68   69   82   94   68   94   90    937   
3    76   81   83   60   99   60   66   70   82   82   76   87    922   
4    67   64   74   60   94   84   94   98   66   64   77   94    936   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
95   97   78   89   64   86   67   63   68   96   78   91   60    937   
96   63   82   82   90   82   60   91   78   91   82   67   75    943   
97   75   64   63   86   67   69   80   86   75   77   85   73    900   
98   81   72   65   70   90   67   81   71   62   94   91   98    942   
99   80   94   99   93   86   75   66   62   88   89   68   82    982   

          avg best_month  
0   74.666667        01월  
1   76.166667        12월  
2   78.083333        09월  
3   76.833333        05월  
4   78.000000        08월  
..        ...        ...  
95  78.083333        01월  
96  78.583333        07월  
97  75.000000        04월  
98  78.500000        12월  
99  81.833333        03월  

[100 rows x 15 columns]

In [254]:
df['worst_month'] = df.columns[np.argmin(df.iloc[:,:-2].values,axis=1)]

In [255]:
df

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
0    98   70   88   77   62   62   60   61   89   81   80   68    896   
1    77   83   61   73   68   82   86   81   73   66   69   95    914   
2    83   76   68   66   79   68   69   82   94   68   94   90    937   
3    76   81   83   60   99   60   66   70   82   82   76   87    922   
4    67   64   74   60   94   84   94   98   66   64   77   94    936   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
95   97   78   89   64   86   67   63   68   96   78   91   60    937   
96   63   82   82   90   82   60   91   78   91   82   67   75    943   
97   75   64   63   86   67   69   80   86   75   77   85   73    900   
98   81   72   65   70   90   67   81   71   62   94   91   98    942   
99   80   94   99   93   86   75   66   62   88   89   68   82    982   

          avg best_month worst_month  
0   74.666667        01월         07월  
1   76.166667        12월         03월  
2   78.083333        09월         04월  
3   76.833333        05월         04월  
4   78.000000        08월         04월  
..        ...        ...         ...  
95  78.083333        01월         12월  
96  78.583333        07월         06월  
97  75.000000        04월         03월  
98  78.500000        12월         09월  
99  81.833333        03월         08월  

[100 rows x 16 columns]

In [256]:
df.iloc[np.argsort(df.total.values)[::-1],:]

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
73   95   80   94   99   99   88   83   96   94   62   87   70   1047   
23   83   97   84   99   95   90   72   92   83   78   89   85   1047   
45   88   90   94   61   86   95   98   99   68   97   98   70   1044   
14   73   93   99   78   95   91   90   95   76   70   87   79   1026   
55   97   72   64   93   99   96   93   69   87   69   85   97   1021   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
29   75   60   90   84   65   81   80   77   61   74   76   70    893   
76   70   71   84   66   65   62   63   96   94   74   70   76    891   
47   68   61   82   91   80   99   75   65   68   66   73   61    889   
20   61   78   72   74   64   67   89   77   66   81   63   81    873   
77   71   67   71   89   73   75   60   72   65   82   60   73    858   

          avg best_month worst_month  
73  87.250000        04월         10월  
23  87.250000        04월         07월  
45  87.000000        08월         04월  
14  85.500000        03월         10월  
55  85.083333        05월         03월  
..        ...        ...         ...  
29  74.416667        03월         02월  
76  74.250000        08월         06월  
47  74.083333        06월         02월  
20  72.750000        07월         01월  
77  71.500000        04월         07월  

[100 rows x 16 columns]

In [257]:
df = df.iloc[np.argsort(df.total.values)[::-1],:]
df.index = np.arange(1,df.shape[0]+1)

In [258]:
df

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
1     95   80   94   99   99   88   83   96   94   62   87   70   1047   
2     83   97   84   99   95   90   72   92   83   78   89   85   1047   
3     88   90   94   61   86   95   98   99   68   97   98   70   1044   
4     73   93   99   78   95   91   90   95   76   70   87   79   1026   
5     97   72   64   93   99   96   93   69   87   69   85   97   1021   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
96    75   60   90   84   65   81   80   77   61   74   76   70    893   
97    70   71   84   66   65   62   63   96   94   74   70   76    891   
98    68   61   82   91   80   99   75   65   68   66   73   61    889   
99    61   78   72   74   64   67   89   77   66   81   63   81    873   
100   71   67   71   89   73   75   60   72   65   82   60   73    858   

           avg best_month worst_month  
1    87.250000        04월         10월  
2    87.250000        04월         07월  
3    87.000000        08월         04월  
4    85.500000        03월         10월  
5    85.083333        05월         03월  
..         ...        ...         ...  
96   74.416667        03월         02월  
97   74.250000        08월         06월  
98   74.083333        06월         02월  
99   72.750000        07월         01월  
100  71.500000        04월         07월  

[100 rows x 16 columns]

In [259]:
#70이하인 값을 1개이하 가지고 있는 사람은 없으면 우수
#70이하인 값 3개 이하인 사람은 보통
#70이하인 값이 5개 이하인 사람은 저조
#70이하인 갑시 5개보다 큰 사람은 아주저조
arr = np.sum(df.iloc[:,:-2] <= 70,axis=1)
score = np.where(arr <= 1,'우수', 
         np.where(arr<=3,'보통',
                np.where(arr<=5,'저조','아주저조')))
df['score'] = score 

In [260]:
# 판다스 2일차

In [261]:
df.head(3)
df.tail(3)

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
98    68   61   82   91   80   99   75   65   68   66   73   61    889   
99    61   78   72   74   64   67   89   77   66   81   63   81    873   
100   71   67   71   89   73   75   60   72   65   82   60   73    858   

           avg best_month worst_month score  
98   74.083333        06월         02월  아주저조  
99   72.750000        07월         01월    저조  
100  71.500000        04월         07월    저조

In [262]:
# 인덱스 재설정
df.reset_index(inplace=True)

In [263]:
# index 컬럼을 제거
df.drop(columns=['index'],inplace=True)
df.head()

01월  02월  03월  04월  05월  06월  07월  08월  09월  10월  11월  12월  total  \
0   95   80   94   99   99   88   83   96   94   62   87   70   1047   
1   83   97   84   99   95   90   72   92   83   78   89   85   1047   
2   88   90   94   61   86   95   98   99   68   97   98   70   1044   
3   73   93   99   78   95   91   90   95   76   70   87   79   1026   
4   97   72   64   93   99   96   93   69   87   69   85   97   1021   

         avg best_month worst_month score  
0  87.250000        04월         10월    보통  
1  87.250000        04월         07월    우수  
2  87.000000        08월         04월    보통  
3  85.500000        03월         10월    우수  
4  85.083333        05월         03월    보통

In [273]:
import warnings
warnings.filterwarnings(action='ignore')

In [ ]:
total = df.iloc[:,:13].sum(axis=0)

In [265]:
df.iloc[:,:13].sum(axis=0)

01월       8040
02월       7856
03월       8147
04월       7961
05월       8065
06월       8165
07월       7987
08월       8063
09월       7885
10월       7859
11월       7987
12월       8049
total    96064
dtype: int64

In [266]:
avg = df.avg.mean()

In [267]:
best_month = np.unique(df.best_month.values)[np.argmax(np.unique(df.best_month.values,return_counts=True)[1])]

In [268]:
worst_month = np.unique(df.worst_month.values)[np.argmax(np.unique(df.worst_month.values,return_counts=True)[1])]

In [269]:
unique_name = np.unique(df.score,return_counts=True)[0]
unique_cnt = np.unique(df.score,return_counts=True)[1]
best_index = np.argmax(unique_cnt)
freq_score = unique_name[best_index]

In [270]:
print(unique_name)
print(unique_cnt)
print(freq_score)

['보통' '아주저조' '우수' '저조']
[43  9 12 36]
보통


In [271]:
# total,avg,best_month,worst_month,freq_score
# 토탈이 어디로 갔을까


In [272]:
new_data = pd.concat([total,
          pd.Series(avg),
          pd.Series(best_month),
          pd.Series(worst_month),
          pd.Series(freq_score)])

In [284]:
df.columns.size

17

In [285]:
df.loc[100] = new_data.values

In [286]:
df.iloc[:,7:].head()

08월  09월  10월  11월  12월  total        avg best_month worst_month score
0   96   94   62   87   70   1047  87.250000        04월         10월    보통
1   92   83   78   89   85   1047  87.250000        04월         07월    우수
2   99   68   97   98   70   1044  87.000000        08월         04월    보통
3   95   76   70   87   79   1026  85.500000        03월         10월    우수
4   69   87   69   85   97   1021  85.083333        05월         03월    보통

In [292]:
def unique_cnt(x):
    unique_name = np.unique(x,return_counts=True)[0]
    unique_cnt = np.unique(x,return_counts=True)[1]
    freq_cnt_index = np.argmax(unique_cnt)
    result = unique_name[freq_cnt_index]
    return result

In [294]:
f = lambda x: np.unique(x,return_count=True)[0][np.argmax(np.unique(x,return_counts=True)[1])]

In [290]:
unique_cnt(df.score)

'보통'

In [291]:
df.loc[:,['best_month','worst_month','score']].apply(unique_cnt,axis=0)

best_month     04월
worst_month    04월
score           보통
dtype: object

In [296]:
np.random.seed(3)
dic = {
    'a':np.random.randint(1,10,5),
    'b':np.random.randint(1,10,5)
}
df1 = pd.DataFrame(dic)

In [297]:
df1

a  b
0  9  6
1  4  4
2  9  6
3  9  8
4  1  7

In [298]:
#df1의 컬럼중
# a>b 이면 a//3
# b>a 이면 b//2
# a == b 이면 a*b
def xx(x):
    if x[0] > x[1]:
        result = x[0] // 3
    elif x[0] < x[1]:
        result = x[1] // 2
    else:
        result = x[0] * x[1]
    return result

In [301]:
df1['result'] = df1.apply(xx,axis=1)

In [302]:
df1.loc[4,'result'] = 7

In [303]:
df1.iloc[4,2] = 3

In [304]:
df1.loc[0,['b','result']] = 3
df1.iloc[0,[1,2]] = 6,3
df1

a  b  result
0  9  6       3
1  4  4      16
2  9  6       3
3  9  8       3
4  1  7       3

In [319]:
dic = {
    '이름':['서준','우현','인아'],
    '수학':[80,80,70],
    '영어':[98,89,95],
    '음악':[85,95,100],
}
df2 = pd.DataFrame(dic)
df2

이름  수학  영어   음악
0  서준  80  98   85
1  우현  80  89   95
2  인아  70  95  100

In [320]:
df2.transpose().T

이름  수학  영어   음악
0  서준  80  98   85
1  우현  80  89   95
2  인아  70  95  100

In [321]:
df2.loc[df2.이름 == '서준','수학']

0    80
Name: 수학, dtype: int64

In [322]:
df2.loc[3] = ['서준',90,80,70]

In [323]:
df2.set_index('이름').loc['서준','수학']

이름
서준    80
서준    90
Name: 수학, dtype: int64

In [324]:
df2

이름  수학  영어   음악
0  서준  80  98   85
1  우현  80  89   95
2  인아  70  95  100
3  서준  90  80   70

In [327]:
df2.loc[df2.이름 == '서준',:]

이름  수학  영어  음악
0  서준  80  98  85
3  서준  90  80  70

In [316]:
pd.__version__
np.__version__

'1.21.5'

In [317]:
np.__version__

'1.21.5'

In [328]:
#set_index(내가가기고 있는 컬럼) 
#reset_index(인덱스컬럼을재변경) --> 인덱스 --> df컬럼변경
#reindex(인덱스) => 재할당
#df.index = 인덱스 ==>재할당
#pd.__version__
#np.__version__

In [330]:
df.reindex()

01월   02월   03월   04월   05월   06월   07월   08월   09월   10월   11월   12월  \
0      95    80    94    99    99    88    83    96    94    62    87    70   
1      83    97    84    99    95    90    72    92    83    78    89    85   
2      88    90    94    61    86    95    98    99    68    97    98    70   
3      73    93    99    78    95    91    90    95    76    70    87    79   
4      97    72    64    93    99    96    93    69    87    69    85    97   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
96     70    71    84    66    65    62    63    96    94    74    70    76   
97     68    61    82    91    80    99    75    65    68    66    73    61   
98     61    78    72    74    64    67    89    77    66    81    63    81   
99     71    67    71    89    73    75    60    72    65    82    60    73   
100  8040  7856  8147  7961  8065  8165  7987  8063  7885  7859  7987  8049   

     total        avg best_month worst_month score  
0     1047  87.250000        04월         10월    보통  
1     1047  87.250000        04월         07월    우수  
2     1044  87.000000        08월         04월    보통  
3     1026  85.500000        03월         10월    우수  
4     1021  85.083333        05월         03월    보통  
..     ...        ...        ...         ...   ...  
96     891  74.250000        08월         06월  아주저조  
97     889  74.083333        06월         02월  아주저조  
98     873  72.750000        07월         01월    저조  
99     858  71.500000        04월         07월    저조  
100  96064  80.053333        04월         04월    보통  

[101 rows x 17 columns]

In [331]:
df = df.iloc[np.random.choice(df.index,df.index.size,replace=False),:]

In [345]:
df.sort_index()

01월   02월   03월   04월   05월   06월   07월   08월   09월   10월   11월   12월  \
0      95    80    94    99    99    88    83    96    94    62    87    70   
1      83    97    84    99    95    90    72    92    83    78    89    85   
2      88    90    94    61    86    95    98    99    68    97    98    70   
3      73    93    99    78    95    91    90    95    76    70    87    79   
4      97    72    64    93    99    96    93    69    87    69    85    97   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
96     70    71    84    66    65    62    63    96    94    74    70    76   
97     68    61    82    91    80    99    75    65    68    66    73    61   
98     61    78    72    74    64    67    89    77    66    81    63    81   
99     71    67    71    89    73    75    60    72    65    82    60    73   
100  8040  7856  8147  7961  8065  8165  7987  8063  7885  7859  7987  8049   

     total        avg best_month worst_month score  
0     1047  87.250000        04월         10월    보통  
1     1047  87.250000        04월         07월    우수  
2     1044  87.000000        08월         04월    보통  
3     1026  85.500000        03월         10월    우수  
4     1021  85.083333        05월         03월    보통  
..     ...        ...        ...         ...   ...  
96     891  74.250000        08월         06월  아주저조  
97     889  74.083333        06월         02월  아주저조  
98     873  72.750000        07월         01월    저조  
99     858  71.500000        04월         07월    저조  
100  96064  80.053333        04월         04월    보통  

[101 rows x 17 columns]

# 판다스 산술연산 시리즈연산

In [18]:
import numpy as np
import pandas as pd

In [19]:
dic = {
    0:1,
    1:2,
    2:3,
}
s1 = pd.Series(dic)

In [20]:
s2 = s1.copy()
s2.index = [2,3,4]
s2

2    1
3    2
4    3
dtype: int64

In [21]:
s1.values

array([1, 2, 3], dtype=int64)

In [22]:
s1.values + s2.values

array([2, 4, 6], dtype=int64)

In [23]:
s1 + s2

0    NaN
1    NaN
2    4.0
3    NaN
4    NaN
dtype: float64

In [24]:
df1 = pd.DataFrame(np.arange(1,5).reshape(2,2))
df2 = pd.DataFrame(np.arange(5,9).reshape(2,2))

In [26]:
print(df1)
print('=====')
print(df2)
df1+df2

   0  1
0  1  2
1  3  4
=====
   0  1
0  5  6
1  7  8


0   1
0   6   8
1  10  12

In [27]:
df1.columns = ['a','b']
df2.columns = ['b','a']

In [28]:
print(df1)
print("=======")
print(df2)
df1+df2

   a  b
0  1  2
1  3  4
   b  a
0  5  6
1  7  8


a   b
0   7   7
1  11  11

In [29]:
df2.columns = ['c','d']
(df1 + df2).shape
df1+df2

a   b   c   d
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN

In [30]:
df2.index = [2,3]
(df1+df2).shape
df1+df2

a   b   c   d
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
3 NaN NaN NaN NaN

In [31]:
(s1+s2).fillna(0)

0    0.0
1    0.0
2    4.0
3    0.0
4    0.0
dtype: float64

In [32]:
s1.add(s2,fill_value=0)

0    1.0
1    2.0
2    4.0
3    2.0
4    3.0
dtype: float64

In [33]:
(s1+s2).fillna(0)

0    0.0
1    0.0
2    4.0
3    0.0
4    0.0
dtype: float64

In [36]:
df = pd.read_csv('train.csv')

In [37]:
df.to_csv('titanic.csv')

In [1]:
import openpyxl

In [2]:
wb = openpyxl.load_workbook('test.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'test.xlsx'

import sys"

In [4]:
# 다른파일 불러 오는거 나중에 해보죠

In [5]:
df.describe()

NameError: name 'df' is not defined

In [ ]:
import