In [180]:
import numpy as np

In [103]:
X = np.random.randn(5,4)
y = np.random.randn(5,1)

In [104]:
X

array([[-0.7474417 , -1.94517219, -0.2855979 , -0.72924845],
       [-2.53119547,  0.46369907,  1.36596576, -0.35578206],
       [-0.97597326,  1.47058189,  1.00471473, -1.86746192],
       [ 0.33301355,  0.03270642, -1.25404576,  0.6585894 ],
       [ 0.4650855 ,  1.01650546,  0.25839173,  0.75351011]])

In [105]:
y

array([[ 0.4919165 ],
       [ 0.1279562 ],
       [-0.20786313],
       [-0.01339165],
       [ 1.29776177]])

In [106]:
w = np.random.randn(4)

In [107]:
def prdict(x):
    return np.dot(x,w)

In [108]:
X

array([[-0.7474417 , -1.94517219, -0.2855979 , -0.72924845],
       [-2.53119547,  0.46369907,  1.36596576, -0.35578206],
       [-0.97597326,  1.47058189,  1.00471473, -1.86746192],
       [ 0.33301355,  0.03270642, -1.25404576,  0.6585894 ],
       [ 0.4650855 ,  1.01650546,  0.25839173,  0.75351011]])

In [109]:
y_hat = prdict(X)

In [110]:
y_hat

array([ 3.18707469, -4.35607827, -2.63433568,  0.17127629, -1.91666705])

In [111]:
Loss = np.abs(y_hat-y)

In [112]:
Loss

array([[2.69515819, 4.84799478, 3.12625218, 0.32064021, 2.40858355],
       [3.05911849, 4.48403447, 2.76229188, 0.04332009, 2.04462325],
       [3.39493782, 4.14821514, 2.42647255, 0.37913942, 1.70880392],
       [3.20046634, 4.34268662, 2.62094403, 0.18466794, 1.9032754 ],
       [1.88931293, 5.65384004, 3.93209744, 1.12648547, 3.21442881]])

In [113]:
y_hat.shape

(5,)

In [114]:
Loss = np.abs(y_hat[0]-y[0])
Loss = np.abs(y_hat[1]-y[1])

In [115]:
np.sum(np.abs(y_hat - y))/5

13.18355819463726

In [116]:
np.mean(np.abs(y_hat-y))

2.636711638927452

In [117]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [118]:
for xs in [(0, 0), (1, 0), (0, 1), (1, 1)]:
    y = AND(xs[0], xs[1])
    print(str(xs) + " -> " + str(y))

(0, 0) -> 0
(1, 0) -> 0
(0, 1) -> 0
(1, 1) -> 1


In [119]:
X = np.array([[0,0],
             [1,0],
             [0,1],
             [1,1]])

In [120]:
y = np.array([[0],
             [0],
             [0],
             [1]])

In [121]:
W = np.array([[0.5],[0.5]])
b = -0.7
def And(X):
    return np.where(np.dot(X,W) + b>=0,1,0)

In [122]:
And(X)

array([[0],
       [0],
       [0],
       [1]])

In [123]:
ws1 = np.linspace(0,1,100)
ws2 = np.linspace(0,1,100)
bs = np.linspace(-1,1,100)

In [124]:
y_and = np.array([[0],[0],[0],[1]])

In [125]:
X[1,[0]]

array([1])

In [127]:
np.sum(np.where(X[:,[0]]*0.5 + X[:,[1]]*0.5 -0.7 >=0 ,1,0) == y_and) == 4

True

In [128]:
w1 = 0.010101010101010102 
w2 = 0.16161616161616163 
b = -0.010101010101010055

In [129]:
W = np.c_[w1,w2].reshape(2,1)

In [159]:
And(X)

array([[0],
       [1],
       [1],
       [1]])

In [161]:
ws1 = np.linspace(0,1,100)
ws2 = np.linspace(0,1,100)
bs = np.linspace(-1,1,100)

In [167]:
y_and = np.array([[0],[0],[0],[1]])

In [168]:
for w1 in ws1:
    for w2 in ws2:
        for b in bs:
            if np.sum(np.where(X[:,[0]]*w1 + X[:,[1]]*w2 +b >=0 ,1,0) == y_and) == 4:
                print(w1,w2,b)
                break

0.010101010101010102 0.020202020202020204 -0.030303030303030276
0.010101010101010102 0.04040404040404041 -0.050505050505050386
0.010101010101010102 0.06060606060606061 -0.07070707070707061
0.010101010101010102 0.08080808080808081 -0.09090909090909083
0.010101010101010102 0.10101010101010102 -0.11111111111111105
0.010101010101010102 0.12121212121212122 -0.13131313131313127
0.010101010101010102 0.14141414141414144 -0.1515151515151515
0.010101010101010102 0.16161616161616163 -0.1717171717171716
0.010101010101010102 0.18181818181818182 -0.19191919191919182
0.010101010101010102 0.20202020202020204 -0.21212121212121204
0.010101010101010102 0.22222222222222224 -0.23232323232323226
0.010101010101010102 0.24242424242424243 -0.2525252525252525
0.010101010101010102 0.26262626262626265 -0.2727272727272727
0.010101010101010102 0.2828282828282829 -0.2929292929292928
0.010101010101010102 0.30303030303030304 -0.31313131313131304
0.010101010101010102 0.32323232323232326 -0.33333333333333326
0.010101010

In [181]:
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [182]:
y_or

array([[0],
       [1],
       [1],
       [1]])

In [183]:
y_xor = np.array([[0],[1],[1],[0]])

In [184]:
w_and1 = 0.010101010101010102 
w_and2 = 0.08080808080808081 
b_and = -0.09090909090909083
w_or1 = 0.010101010101010102 
w_or2 = 0.030303030303030304 
b_or = -0.010101010101010055

In [185]:
y_nand = np.array([[1],[1],[1],[0]])

In [186]:
w_nand1 = -w_and1
w_nand2 = -w_and2
b_nand = -b_and

In [187]:
test_x = np.array([[1,0],[1,1],[1,1],[0,1]])
test_x

array([[1, 0],
       [1, 1],
       [1, 1],
       [0, 1]])

In [188]:
nand_ = np.array([w_nand1,w_nand2])
or_ = np.array([w_or1, w_or2])

In [189]:
w_1 = np.c_[nand_,or_]

In [190]:
b_1 = np.c_[b_nand,b_or]
b_1.shape

(1, 2)

In [192]:
out_1 = np.dot(X,w_1) + b_1
out_1 = np.where(out_1 >=0,1,0)
w_2 = np.concatenate()

TypeError: concatenate() missing 1 required positional argument: 'arrays'