In [7]:
import numpy as np

In [8]:
X = np.random.randn(100)
y = X*3 +4

In [9]:
np.c_[X,y]

array([[-0.80553584,  1.58339248],
       [ 0.94139052,  6.82417156],
       [ 1.03929768,  7.11789305],
       [-1.40149137, -0.20447412],
       [-0.11559405,  3.65321786],
       [ 0.72147019,  6.16441056],
       [ 1.13637022,  7.40911066],
       [-3.69535774, -7.08607322],
       [ 0.01177258,  4.03531774],
       [ 1.45207578,  8.35622733],
       [-0.31038104,  3.06885688],
       [ 0.1052259 ,  4.31567769],
       [ 1.82023818,  9.46071455],
       [ 0.4258989 ,  5.2776967 ],
       [-1.01310524,  0.96068428],
       [-1.30902912,  0.07291263],
       [-2.07025994, -2.21077982],
       [ 0.72293958,  6.16881875],
       [ 1.21211996,  7.63635989],
       [-0.14631362,  3.56105915],
       [-0.42615183,  2.7215445 ],
       [-0.37366933,  2.87899201],
       [ 0.23387218,  4.70161654],
       [ 2.21902356, 10.65707068],
       [ 0.35177294,  5.05531882],
       [ 0.86915358,  6.60746074],
       [-0.70779439,  1.87661684],
       [-0.90530719,  1.28407843],
       [ 0.96135194,

In [10]:
for i in range(10000):
    y_hat = a*X + b
    loss = np.mean((y-y_hat)**2)
    da = np.mean(2*X*(y_hat-y))
    db = np.mean((y_hat-y))
    a = a - 1e-3*da
    b = b - 1e-3*db

NameError: name 'a' is not defined

In [11]:
X = np.random.randn(100,2)
x1 = X[:,0]
x2 = X[:,1]
y = x1*8 + x2*3 + 10

In [12]:
a1 = 100
a2 = -3
b = 0

In [13]:
for i in range(100000):
    y_hat = a1*x1 + a2*x2 + b
    loss = np.mean((y_hat-y)**2)
    da1 = np.mean(2*x1*(y_hat-y))
    da2 = np.mean(2*x2*(y_hat-y))
    db = np.mean(2*(y_hat-y))
    a1 = a1 - 1e-3*da1
    a2 = a2 - 1e-3*da2
    b = b - 1e-3*db

In [14]:
a1, a2, b

(8.000000000000508, 2.99999999999983, 10.000000000000464)

In [15]:
# 위 식을 행렬식으로 바꿈
X = np.random.randn(100,3)
W = np.array([[100],[7],[-20]])
y = np.dot(X,W) + 80
y = y.reshape(-1,1)

In [16]:
W = np.random.randn(3,1)
b = 0

In [17]:
W = np.random.randn(3,1)
b = 0
y_hat = np.dot(X,W) + b
loss = np.mean((y_hat-y)**2)
dw = np.mean(2*np.dot(X.T,(y_hat-y)))
db = np.mean(2*(y_hat-y))
W = W - 1e-3*dw
b = b - 1e-3*db

In [18]:
np.dot(X.T,(y_hat-y))

array([[-10444.31899457],
       [   341.86437022],
       [  2005.26264697]])

In [19]:
for i in range(10000):
    y_hat = np.dot(X,W) + b
    loss = np.mean((y_hat-y)**2)
    dw = 2*np.dot(X.T,(y_hat-y))
    db = np.mean(2*(y_hat-y))
    W = W - 1e-4*dw
    b = b - 1e-4*db

In [20]:
(y_hat - y.reshape(100,1)).shape

(100, 1)

In [21]:
X = np.random.randn(100,20)
y = np.dot(X,np.random.randn(20,1)) + 100

In [22]:
W = np.random.randn(20,1)
b = 0
for i in range(10000):
    y_hat = np.dot(X,W) + b
    loss = np.mean((y_hat-y)**2)
    dw = np.dot(X.T,(y_hat-y))
    db = np.mean(2*(y_hat-y))
    W = W - 1e-4*dw
    b = b - 1e-4*db

In [23]:
X = np.around(np.random.randn(100),2)
y = X*3

In [24]:
##1 가설함수
##2 loss function
##3 loss 미분(미분식, [수치적방법])
##4 미분값을 가설함수의 변수값 빼주면 (최적화)
##5 학습 (2~4)까지 반복
w = np.random.randn(1)
b = 0
h = 1e-4
for i in range(10000):
    y_hat = w*X + b
    loss = np.mean((y_hat-y)**2)
    fx = np.mean((y_hat-y)**2)
    y_hat_tmp = (w+h)*X + b
    fxh = np.mean((y_hat_tmp -y)**2)
    dw = (fxh-fx)/h
    fx = np.mean((y_hat-y)**2)
    y_hat_tmp = w*X +(b+h)
    fxh = np.mean((y_hat_tmp-y)**2)
    db = (fxh-fx)/h
    w = w - 1e-3*dw
    b = b - 1e-3*db

In [25]:
X = np.random.randn(100)
y = X*7

In [26]:
# 예측함수
# 비용함수
# 미분함수
#1 예측함수
def predict(w):
    return X*w
#2 비용 함수
def loss(w):
    return np.mean((predict(w)-y)**2)
#3 미분함수
def grad(w):
    h = 1e-4
    fx = loss(w)
    fxh = loss(w+h)
    grad = (fxh-fx)/h
    return grad 
#4 경사하강
def descent_grad(w):
    w = w - 1e-3*grad(w)

In [27]:
w = np.random.randn(1)

In [28]:
w

array([-1.98109786])

In [29]:
print(w)
descent_grad(w)
print(w)

[-1.98109786]
[-1.98109786]


In [30]:
X = np.random.randn(100)
y = X*100 -70

In [31]:
w = np.array((np.random.randn(1),0))


C:\Users\bjlov\AppData\Local\Temp\ipykernel_15024\863607374.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  w = np.array((np.random.randn(1),0))


In [32]:
def predict(w):
    y_hat = X*w[0] + w[1] 
    return y_hat
def loss(w):
    y_hat = predict(w)
    return np.mean(2*(y_hat-y)**2)
def grad(w):
    h = 1e-4
    fx = loss(w)
    tmp = w[0]
    w[0] = tmp+h
    fxh = loss(w)
    dw = (fxh-fx)/h
    w[0] = tmp
    tmp = w[1]
    fx = loss(w)
    w[1] = tmp+h
    fxh = loss(w)
    db = (fxh-fx)/h
    result = np.array((dw,db))
    return result

In [33]:
grad(w)

array([-452.1899578 ,  224.74477206])

In [34]:
fx = loss(w)

In [35]:
tmp = w[0]
w[0] = tmp+h

In [36]:
fxh = loss(w)

In [37]:
w[0]

array([-0.73502325])

In [38]:
X = np.random.randn(100,2)
W = np.array([[8],[-7]])
y = np.dot(X,W) + 1000

In [39]:
X.shape, y.shape

((100, 2), (100, 1))

In [40]:
w = np.random.randn(2,1)
b = 0
W = np.array((w,b))

C:\Users\bjlov\AppData\Local\Temp\ipykernel_15024\1050238314.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W = np.array((w,b))


In [41]:
W

array([array([[-0.34734147],
              [-1.59541089]]), 0], dtype=object)

In [42]:
def predict(W):
    y_hat = np.dot(X,W[0]) + W[1]
    return y_hat
def loss(W):
    y_hat = predict(W)
    return np.mean(2*(y_hat-y)**2)
def grad(W):
    h = 1e-4
    tmp = W[0][0]
    fx = loss(W)
    W[0][0] = tmp + h
    fxh = loss(W)
    grad_1 = (fxh-fx)/h
    W[0][0] = tmp
    fx = loss(W)
    tmp = W[0][1]
    W[0][1] = tmp+h
    fxh = loss(W)
    grad_2 = (fxh-fx)/h
    W[0][1] = tmp
    tmp = W[1]
    fx = loss(W)
    W[1] = tmp + h
    fxh = loss(W)
    grad_b = (fxh - fx)/h
    w_ = np.c_[grad_1, grad_2].T
    grad = np.array((w_,grad_b))
    return grad

In [43]:
grad(W)

C:\Users\bjlov\AppData\Local\Temp\ipykernel_15024\2720279532.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  grad = np.array((w_,grad_b))


array([array([[662.91148076],
              [ 39.22496224]]), -3994.3264657631516], dtype=object)

In [44]:
for i in range(10000):
    W[0] = W[0] - 1e-3*grad(W)[0]
    W[1] = W[1] - 1e-3*grad(W)[1]

C:\Users\bjlov\AppData\Local\Temp\ipykernel_15024\2720279532.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  grad = np.array((w_,grad_b))


In [69]:
def grad(W):
    h = 1e-4
    grad_w = np.zeros_like(W[0])
    for i in range(W[0].shape[0]):
        for j in range(W[0].shape[1]):
            tmp = W[0][i,j]
            fx = loss(W)
            W[0][i,j] = tmp+h
            fxh = loss(W)
            grad_w[i,j] = (fxh-fx)/h
            W[0][i,j] = tmp
    tmp = W[1]
    fx = loss(W)
    W[1] = tmp+h
    fxh = loss(W)
    grad_b = (fxh-fx)/h
    W[1] = tmp
    grad = np.array((grad_w,grad_b))
    return grad

In [70]:
X = np.random.randn(100,3)
w1 = np.random.randn(3,10)
b1 = np.random.randn(1,10)
w2 = np.random.randn(10,1)
b2 = np.random.randn(1,1)
y = np.dot(X,w1) + b1
y = np.dot(y,w2) + b2

In [71]:
W = [
    [w1,b1],
    [w2,b2]
]

In [72]:
W = [
    [w1,b1],
    [w2,b2]
]

In [73]:
def predict(W):
    y_hat = X.copy()
    for i in range(len(W)):
        y_hat = np.dot(y_hat,W[i][0]) + W[i][1]
    return y_hat

In [74]:
def predict(W):
    y_hat = X.copy()
    for i in range(len(W)):
        y_hat = np.dot(y_hat,W[i][0]) + W[i][1]
    return y_hat

def loss(W):
    y_hat = predict(W)
    return np.mean((y_hat-y)**2)

def grad(W):
    h = 1e-4
    grad_ = []
    for i in range(len(W)):
        grad_w = np.zeros_like(W[i][0])
        for row in range(W[i][0].shape[0]):
            for col in range(W[i][0].shape[1]):
                tmp = W[i][0][row,col]
                fx = loss(W)
                W[i][0][row,col] = tmp+h
                fxh = loss(W)
                grad_w[row,col] = (fxh-fx)/h
                W[i][0][row,col] = tmp
        grad_b = []
        for row in range(W[i][1].size):
            tmp = W[i][1][:,row]
            fx = loss(W)
            W[i][1][:,row] = tmp+h
            fxh = loss(W)
            grad_b.append((fxh-fx)/h)
            W[i][1][:,row] = tmp
        grad_b = np.array(grad_b).reshape(1,-1)
        grad_tmp = [grad_w,grad_b]
        grad_.append(grad_tmp)
    return grad_

In [75]:
for i in range(10):
    for j in range(len(W)):
        W[j][0] = W[j][0] - 1e-3*grad(W)[j][0]
        W[j][1] = W[j][1] - 1e-3*grad(W)[j][1]

In [76]:
X = np.random.randn(10000,200)
W = net([30,100,1])

In [77]:
y = predict(W)

In [80]:
W = net([30,100,1])

In [81]:
def net(values):
    net = []
    row = X.shape[1]
    for value in values: 
        w = np.random.randn(row,value)
        b = np.random.randn(1,value)
        row = value
        tmp = [w,b]
        net.append(tmp)
    return net

In [82]:
for i in range(10000):
    W[0] = W[0] - 1e-3*grad(W)[0]
    W[1] = W[1] - 1e-3*grad(W)[1]

TypeError: can't multiply sequence by non-int of type 'float'