In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [42]:
df = sns.load_dataset('titanic')

In [43]:
df.isna()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False       False   True        False  False  False  
1    False       False  False        False  False  False  
2    False       False   True        False  False  False  
3    False       False  False        False  False  False  
4    False       False   True        False  False  False  
..     ...         ...    ...          ...    ...    ...  
886  False       False   True        False  False  False  
887  False       False  False        False  False  False  
888  False       False   True        False  False  False  
889  False       False  False        False  False  False  
890  False       False   True        False  False  False  

[891 rows x 15 columns]

In [44]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [45]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [46]:
df.loc[df.embark_town.isna(),:]

survived  pclass     sex   age  sibsp  parch  fare embarked  class  \
61          1       1  female  38.0      0      0  80.0      NaN  First   
829         1       1  female  62.0      0      0  80.0      NaN  First   

       who  adult_male deck embark_town alive  alone  
61   woman       False    B         NaN   yes   True  
829  woman       False    B         NaN   yes   True

In [47]:
df.deck.value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

In [48]:
df.deck.value_counts(dropna=False)

NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: deck, dtype: int64

In [49]:
df.deck.isna()
# 누락 데이터

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: deck, Length: 891, dtype: bool

In [50]:
~df.deck.isna()
# 누락 안된 데이터

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887     True
888    False
889     True
890    False
Name: deck, Length: 891, dtype: bool

In [51]:
df.isna().sum().sort_values()[::-1]

deck           688
age            177
embark_town      2
embarked         2
alone            0
alive            0
adult_male       0
who              0
class            0
fare             0
parch            0
sibsp            0
sex              0
pclass           0
survived         0
dtype: int64

In [52]:
np.around(df.isna().sum().sort_values()[::-1]/df.shape[0],2)

deck           0.77
age            0.20
embark_town    0.00
embarked       0.00
alone          0.00
alive          0.00
adult_male     0.00
who            0.00
class          0.00
fare           0.00
parch          0.00
sibsp          0.00
sex            0.00
pclass         0.00
survived       0.00
dtype: float64

In [53]:
raw_df = df.copy()
# 원본 다날리는거 방지용

In [54]:
raw_df.shape

(891, 15)

In [55]:
# row 지운다
df = df.loc[~df.deck.isna(),:]

In [56]:
df.shape

(203, 15)

In [57]:
df.isna().sum().sort_values()[::-1]

age            19
embark_town     2
embarked        2
alone           0
alive           0
deck            0
adult_male      0
who             0
class           0
fare            0
parch           0
sibsp           0
sex             0
pclass          0
survived        0
dtype: int64

In [58]:
df.shape[0]/raw_df.shape[0]

0.22783389450056116

In [59]:
# 72퍼였는데 지우고나니까 22퍼

In [60]:
df = raw_df

In [61]:
df.shape

(891, 15)

In [62]:
df.drop(columns=['deck']).isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [65]:
df.drop(columns=['deck'],inplace=True)

In [67]:
df.shape
# 열이 하나 사라진 모습

(891, 14)

In [71]:
# 891과 714는 안맞다

In [68]:
df.age.size

891

In [70]:
df.age.dropna().size

714

In [72]:
df.loc[df.embarked.isna()]

survived  pclass     sex   age  sibsp  parch  fare embarked  class  \
61          1       1  female  38.0      0      0  80.0      NaN  First   
829         1       1  female  62.0      0      0  80.0      NaN  First   

       who  adult_male embark_town alive  alone  
61   woman       False         NaN   yes   True  
829  woman       False         NaN   yes   True

In [76]:
df = df.loc[~df.embarked.isna()]

In [74]:
# index를 찾아서 drop으로 지우든가 loc 저렇게 지워도되고

In [77]:
df.shape

(889, 14)

In [78]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [80]:
# age만 남았다 => 지우기 불가능?

In [81]:
df = pd.DataFrame()

In [82]:
df['c1'] = ['a','a','b','a','b']
df['c2'] = [1,1,1,2,2]
df['c3'] = [1,1,2,2,2]

In [83]:
df

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [84]:
# duplicated

In [86]:
df[df.duplicated()]

c1  c2  c3
1  a   1   1

In [85]:
df[~df.duplicated()]

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [87]:
df.loc[5] = ['a',1,1]

In [91]:
df

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2
5  a   1   1

In [88]:
df.duplicated(keep='last')

0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [90]:
~df.duplicated(keep='last')

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [ ]:
df.iloc[0,:]

c1    a
c2    1
c3    1
Name: 0, dtype: object

In [98]:
df.shape[1]

3

In [101]:
sum(df.iloc[0,:] == df.iloc[1,:]) == df.shape[1]
sum(df.iloc[0,:] == df.iloc[2,:]) == df.shape[1]
sum(df.iloc[0,:] == df.iloc[3,:]) == df.shape[1]
sum(df.iloc[0,:] == df.iloc[4,:]) == df.shape[1]
sum(df.iloc[0,:] == df.iloc[5,:]) == df.shape[1]
sum(df.iloc[1,:] == df.iloc[2,:]) == df.shape[1]
sum(df.iloc[1,:] == df.iloc[3,:]) == df.shape[1]
sum(df.iloc[1,:] == df.iloc[4,:]) == df.shape[1]
sum(df.iloc[1,:] == df.iloc[5,:]) == df.shape[1]
sum(df.iloc[2,:] == df.iloc[3,:]) == df.shape[1]
sum(df.iloc[2,:] == df.iloc[4,:]) == df.shape[1]
sum(df.iloc[2,:] == df.iloc[5,:]) == df.shape[1]
sum(df.iloc[3,:] == df.iloc[4,:]) == df.shape[1]
sum(df.iloc[3,:] == df.iloc[5,:]) == df.shape[1]
sum(df.iloc[4,:] == df.iloc[5,:]) == df.shape[1]

# 이런 논리로 돌아간다

False

In [130]:
df

c1  c2  c3
0  a   1   1
1  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2
5  a   1   1

In [144]:
keep = 'first'
dup = []
for i in range(df.shape[0]-1):
    for j in range(df.shape[0]-i-1):
        if sum(df.iloc[i,:] == df.iloc[j+i+1,:]) == df.shape[1]:
            first = i
            last = j+i+1
            if keep == 'first':
                dup.append(last)
            else:
                dup.append(first)

dup = np.unique(dup)
result = np.full(df.shape[0],False)
result[dup] = True
df.loc[~result,:]
                          
                    

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [145]:
# 중복된 항목 지우기 완료

In [148]:
def my_duplicate(df,keep='first'):
    keep = 'first'
    dup = []
    for i in range(df.shape[0]-1):
        for j in range(df.shape[0]-i-1):
            if sum(df.iloc[i,:] == df.iloc[j+i+1,:]) == df.shape[1]:
                first = i
                last = j+i+1
                if keep == 'first':
                    dup.append(last)
                else:
                    dup.append(first)

    dup = np.unique(dup)
    result = np.full(df.shape[0],False)
    result[dup] = True
    return result
                    

In [149]:
# 함수로 만들어 봤어요

In [150]:
my_duplicate(df)

array([False,  True, False, False, False,  True])

In [153]:
df.loc[~my_duplicate(df),:]

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [160]:
df.loc[~my_duplicate(df,keep='last'),:]

# 왜 마지막행만 남기지않는가

c1  c2  c3
0  a   1   1
2  b   1   2
3  a   2   2
4  b   2   2

In [162]:
import sklearn

In [166]:
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

In [167]:
data = datasets.load_iris()

In [168]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [169]:
df = pd.DataFrame(data['data'],columns=data['feature_names'])

In [170]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [171]:
sc = StandardScaler()
sc.fit(df)

StandardScaler()

In [176]:
sc.transform(df).shape

(150, 4)

In [178]:
df.shape

(150, 4)

In [180]:
np.max(df.values) - np.min(df.values)

7.800000000000001

In [181]:
np.max(sc.transform(df)) - np.min(sc.transform(df))

5.524722390207515

In [186]:
# 이렇게는 안하는게 좋다
# sc.fit_trasform(df)
# fit, transform은 따로 쓰자!

In [187]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [188]:
df.iloc[:,0]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [189]:
df.iloc[:,0].std()

0.8280661279778629

In [195]:
(df.iloc[:,0] - df.iloc[:,0].mean())  / df.iloc[:,0].std()

0     -0.897674
1     -1.139200
2     -1.380727
3     -1.501490
4     -1.018437
         ...   
145    1.034539
146    0.551486
147    0.793012
148    0.430722
149    0.068433
Name: sepal length (cm), Length: 150, dtype: float64

In [213]:
def standard_scaler(df):
    result = np.zeros_like(df)
    for i in range(df.columns.size):
        result[:,i] = (df.iloc[:,i] - df.iloc[:,i].mean() ) / df.iloc[:,i].std()
        return result[:,i]

In [214]:
standard_scaler(df)

array([-0.89767388, -1.13920048, -1.38072709, -1.50149039, -1.01843718,
       -0.53538397, -1.50149039, -1.01843718, -1.74301699, -1.13920048,
       -0.53538397, -1.25996379, -1.25996379, -1.8637803 , -0.05233076,
       -0.17309407, -0.53538397, -0.89767388, -0.17309407, -0.89767388,
       -0.53538397, -0.89767388, -1.50149039, -0.89767388, -1.25996379,
       -1.01843718, -1.01843718, -0.77691058, -0.77691058, -1.38072709,
       -1.25996379, -0.53538397, -0.77691058, -0.41462067, -1.13920048,
       -1.01843718, -0.41462067, -1.13920048, -1.74301699, -0.89767388,
       -1.01843718, -1.62225369, -1.74301699, -1.01843718, -0.89767388,
       -1.25996379, -0.89767388, -1.50149039, -0.65614727, -1.01843718,
        1.39682886,  0.67224905,  1.27606556, -0.41462067,  0.79301235,
       -0.17309407,  0.55148575, -1.13920048,  0.91377565, -0.77691058,
       -1.01843718,  0.06843254,  0.18919584,  0.30995914, -0.29385737,
        1.03453895, -0.29385737, -0.05233076,  0.43072244, -0.29

In [215]:
standard_scaler(df).shape

(150,)

In [218]:
def minmax_scaler(df):
    result = np.zeros_like(df)
    for i in range(df.columns.size):
        result[:,i] = ( df.iloc[:,i] - df.iloc[:,i].min() ) / (df.iloc[:,i].max() - df.iloc[:,i].min())
    return result

In [219]:
minmax_scaler(df)

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [221]:
# MinMaxScaler : 자기자신 - min / max - min 

In [222]:
titanic = sns.load_dataset('titanic')

In [225]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [227]:
age = titanic.age.fillna(titanic.age.mean())

In [228]:
age

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [229]:
pd.cut(age,5)

0      (16.336, 32.252]
1      (32.252, 48.168]
2      (16.336, 32.252]
3      (32.252, 48.168]
4      (32.252, 48.168]
             ...       
886    (16.336, 32.252]
887    (16.336, 32.252]
888    (16.336, 32.252]
889    (16.336, 32.252]
890    (16.336, 32.252]
Name: age, Length: 891, dtype: category
Categories (5, interval[float64, right]): [(0.34, 16.336] < (16.336, 32.252] < (32.252, 48.168] < (48.168, 64.084] < (64.084, 80.0]]

In [231]:
pd.cut(age,5).dtype

CategoricalDtype(categories=[(0.34, 16.336], (16.336, 32.252], (32.252, 48.168], (48.168, 64.084], (64.084, 80.0]], ordered=True)

In [235]:
np.linspace(1,10,5)

#구간 5개로 나눠주는 메서드

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [239]:
np.linspace(age.min(),age.max(),6)

# cut 이외에도 linsapce를 애용할것

array([ 0.42 , 16.336, 32.252, 48.168, 64.084, 80.   ])

In [241]:
day = np.datetime64('2022-01-01') + np.arange(365)

In [243]:
sales = np.random.randint(60,100,day.size)

In [244]:
location = np.random.choice(['서울','부산','세종'],day.size)

In [246]:
sales_report = pd.DataFrame()
sales_report['day'] = day
sales_report['location'] = location
sales_report['sales'] = sales

In [247]:
sales_report.head()

day location  sales
0 2022-01-01       서울     74
1 2022-01-02       세종     89
2 2022-01-03       서울     90
3 2022-01-04       서울     96
4 2022-01-05       부산     74

In [248]:
# 그룹으로 묶어보자

In [249]:
sales_report.dtypes

day         datetime64[ns]
location            object
sales                int32
dtype: object

In [251]:
day_str = sales_report.day.astype('str')

In [252]:
sales_report['day_str'] = day_str

In [255]:
sales_report.loc[sales_report.day_str.str.slice(5,7) == '01']

day location  sales     day_str
0  2022-01-01       서울     74  2022-01-01
1  2022-01-02       세종     89  2022-01-02
2  2022-01-03       서울     90  2022-01-03
3  2022-01-04       서울     96  2022-01-04
4  2022-01-05       부산     74  2022-01-05
5  2022-01-06       세종     84  2022-01-06
6  2022-01-07       부산     72  2022-01-07
7  2022-01-08       부산     75  2022-01-08
8  2022-01-09       부산     97  2022-01-09
9  2022-01-10       부산     96  2022-01-10
10 2022-01-11       부산     94  2022-01-11
11 2022-01-12       서울     84  2022-01-12
12 2022-01-13       세종     60  2022-01-13
13 2022-01-14       서울     61  2022-01-14
14 2022-01-15       세종     68  2022-01-15
15 2022-01-16       서울     71  2022-01-16
16 2022-01-17       서울     93  2022-01-17
17 2022-01-18       서울     92  2022-01-18
18 2022-01-19       서울     81  2022-01-19
19 2022-01-20       부산     78  2022-01-20
20 2022-01-21       부산     93  2022-01-21
21 2022-01-22       부산     70  2022-01-22
22 2022-01-23       서울     63  2022-01-23
23 2022-01-24       서울     60  2022-01-24
24 2022-01-25       세종     60  2022-01-25
25 2022-01-26       서울     60  2022-01-26
26 2022-01-27       부산     90  2022-01-27
27 2022-01-28       서울     87  2022-01-28
28 2022-01-29       부산     94  2022-01-29
29 2022-01-30       서울     90  2022-01-30
30 2022-01-31       세종     80  2022-01-31

In [256]:
sales_report.value_counts(['day_str','location'])

day_str     location
2022-01-01  서울          1
2022-09-09  세종          1
2022-09-07  서울          1
2022-09-06  서울          1
2022-09-05  서울          1
                       ..
2022-05-01  서울          1
2022-04-30  부산          1
2022-04-29  서울          1
2022-04-28  부산          1
2022-12-31  부산          1
Length: 365, dtype: int64

In [258]:
sales_report.groupby(['day_str','location']).sum().reset_index()

day_str location  sales
0    2022-01-01       서울     74
1    2022-01-02       세종     89
2    2022-01-03       서울     90
3    2022-01-04       서울     96
4    2022-01-05       부산     74
..          ...      ...    ...
360  2022-12-27       서울     60
361  2022-12-28       서울     77
362  2022-12-29       서울     97
363  2022-12-30       세종     73
364  2022-12-31       부산     96

[365 rows x 3 columns]

In [259]:
month = sales_report.day_str.str.slice(5,7)

In [260]:
sales_report['month'] = month

In [261]:
sales_report

day location  sales     day_str month
0   2022-01-01       서울     74  2022-01-01    01
1   2022-01-02       세종     89  2022-01-02    01
2   2022-01-03       서울     90  2022-01-03    01
3   2022-01-04       서울     96  2022-01-04    01
4   2022-01-05       부산     74  2022-01-05    01
..         ...      ...    ...         ...   ...
360 2022-12-27       서울     60  2022-12-27    12
361 2022-12-28       서울     77  2022-12-28    12
362 2022-12-29       서울     97  2022-12-29    12
363 2022-12-30       세종     73  2022-12-30    12
364 2022-12-31       부산     96  2022-12-31    12

[365 rows x 5 columns]

In [268]:
sales_total = sales_report.groupby(['month','location']).sum().reset_index()

In [269]:
sales_total.head()

month location  sales
0    01       부산    933
1    01       서울   1102
2    01       세종    441
3    02       부산    696
4    02       서울   1078

In [273]:
sales_pivot = sales_total.pivot(index=['location'],columns=['month'],values=['sales'])

In [274]:
sales_pivot

sales                                                               
month       01    02   03   04    05    06   07    08    09    10    11    12
location                                                                     
부산         933   696  765  805   867   747  923  1029   530   659   479   675
서울        1102  1078  815  825  1184  1267  914   642  1049   691  1482   578
세종         441   481  948  643   430   482  626   857   754  1128   386  1192

In [275]:
sales_pivot.columns = ['month_' + j for _,j in sales_pivot.columns]

In [ ]:
sales_pivot.iloc[1,1]=np.nan
sales_pivot.iloc[2